# build stage
FROM node:lts-alpine as build-stage

WORKDIR /app

COPY ./client/package*.json ./
RUN npm install

COPY ./client .
RUN npm run build

# production-stage
FROM nginx:latest as production-stage

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]