version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000
      - 5000
    depends_on:
      - mysql_server

  client:
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8080:80

  mysql_server:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat
